### ISSUE TITLE
bug report: unknown Go version

### ISSUE THREAD

**Issue by tokiwong** [rsc/goversion#18]
OS Version: Mac OS Catalina
Go Version: go1.16.4 darwin/amd64

Hello, following https://docs.solo.io/gloo-mesh/latest/setup/istio_fips/ to verify fips and after running `go get github.com/rsc/goversion`:

running into 
```
➜ goversion -crypto /tmp/pilot-discovery                     

/tmp/pilot-discovery unknown Go version
```

**Comment by infa-ddeore** [comment]
@tokiwong how is this issue fixed?
