### ISSUE TITLE
Executable files never identified on "windows"

### ISSUE THREAD

**Issue by rivy** [rsc/goversion#3]
The application doesn't correctly identify executable files on "windows".

[`info.Mode()&0111 == 0`](https://github.com/rsc/goversion/blob/04f0b81a96346cb33d48044cbffd24c8f57785ad/main.go#L145) is always true on "windows" machines, even if the file is actually executable.

I've opened a [PR (goversion: improve portability)](https://github.com/rsc/goversion/pull/2), using `GOEXE` and file extension comparison, to fix the problem. I hope it's helpful.

**Comment by rsc** [comment]
Fixed by e2aeda8
